server:
    port: 8088

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka


spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    application:
        name: ApiGateway
    cloud.gateway:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
        routes:
        - id: paymodule
          uri: lb://SIMPLE-PAYMENT-SERVICE
          predicates:
            - Path=/api/**
          filters:
          - name: Hystrix
            args:
              name: fallbackCommand
              fallbackUri: forward:/fallback/message
        - id: rewritepath_route
          uri: lb://SIMPLE-PAYMENT-SERVICE
          predicates:
            - Path=/pyts/**
          filters:
            - RewritePath=/pyts/(?<segment>.*),/api/$\{segment}
